experiment_name: demo_roco_biomedclip
device: auto

dataset:
  name: roco
  params:
    zip_path: data/dataset_roco.zip
    split: validation
    n_rows: all
    columns:
      image_key: name
      caption_key: caption
      images_subdir: all_data/validation/radiology/images

model:
  name: biomedclip
  params:
    model_name: hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224

